### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by petrklus** [steve-bate/openhab2-jython#2]
Hello!

I have been scratching my head on this one... how does one get started? Just a simple step-by-step guide would be great! I am already running latest snapshot OH build, I just need to know how to get this one integrated.

**Comment by schnidrig** [comment]
maybe this will help: https://github.com/eclipse/smarthome/wiki/Scripted-Rule-Support

**Comment by steve-bate** [comment]
There is also documentation now at http://docs.openhab.org/configuration/jsr223.html.

(I apologize I didn't see this earlier. GitHub often does not send me notifications when issues are created.)
